# Generated by Django 6.0.2 on 2026-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orthophoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lahan', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='orthophoto/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('detected_count', models.IntegerField(default=0)),
                ('image_with_boxes', models.ImageField(blank=True, null=True, upload_to='orthophoto_boxes/')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
