# Generated by Django 6.0.2 on 2026-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_detectionresult_boundingbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='manual_count',
            field=models.IntegerField(default=0),
        ),
    ]
