# Generated by Django 6.0.3 on 2026-06-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_detectionresult_manual_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('lahan', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=500)),
                ('bbox_path', models.CharField(max_length=500)),
                ('total_terdeteksi', models.IntegerField(default=0)),
                ('kelas_dominan', models.CharField(blank=True, max_length=20)),
                ('range_dominan', models.CharField(blank=True, max_length=50)),
                ('jumlah_dominan', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BobotDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=20)),
                ('range_bobot', models.CharField(max_length=50)),
                ('warna_marker', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='counter.bobotresult')),
            ],
        ),
    ]
