# Generated by Django 6.0.3 on 2026-06-28 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_bobotresult_bobotdetection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bobotresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bobot_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
